ARG REDIS_BASE_IMAGE=docker.m.daocloud.io/library/redis:7.2-alpine
FROM ${REDIS_BASE_IMAGE}

COPY docker/redis/redis.conf /usr/local/etc/redis/redis.conf

RUN mkdir -p /data && chown -R redis:redis /data

USER redis
EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
