import {
  AttendanceRecordResponseDto,
  AttendanceStatisticsResponseDto,
  AuthProfileResponseDto,
  AuthUserResponseDto,
  CheckInResponseDto,
  ClassEnrollmentResponseDto,
  ClassResponseDto,
  CoachResponseDto,
  CourseTypeResponseDto,
  GroupResponseDto,
  HealthResponseDto,
  LeaveRequestResponseDto,
  LessonStatisticsResponseDto,
  LessonTransactionResponseDto,
  LoginResponseDto,
  MembershipDetailResponseDto,
  MembershipResponseDto,
  MessageResponseDto,
  OkResponseDto,
  OrderResponseDto,
  PaginatedCoachResponseDto,
  PaginatedOrderResponseDto,
  PaginatedScheduleResponseDto,
  PaginatedStudentResponseDto,
  QrTokenResponseDto,
  ReadinessResponseDto,
  RevenueStatisticsResponseDto,
  ScheduleResponseDto,
  StudentResponseDto,
  TagResponseDto,
  VenueResponseDto,
} from './dto/responses.dto';
import { PaymentCallbackDto } from '../../modules/billing/dto/payment-callback.dto';
import { ApiErrorResponseDto } from './api-error.dto';
import { PaginatedMetaDto, PaginationQueryDto } from './api-pagination.dto';

/** 注册到 Swagger Document，供 $ref 与分页 schema 使用 */
export const SWAGGER_EXTRA_MODELS = [
  ApiErrorResponseDto,
  PaginationQueryDto,
  PaginatedMetaDto,
  OkResponseDto,
  MessageResponseDto,
  LoginResponseDto,
  AuthProfileResponseDto,
  AuthUserResponseDto,
  StudentResponseDto,
  PaginatedStudentResponseDto,
  TagResponseDto,
  GroupResponseDto,
  CoachResponseDto,
  PaginatedCoachResponseDto,
  CourseTypeResponseDto,
  VenueResponseDto,
  ClassResponseDto,
  ScheduleResponseDto,
  PaginatedScheduleResponseDto,
  MembershipResponseDto,
  MembershipDetailResponseDto,
  LessonTransactionResponseDto,
  ClassEnrollmentResponseDto,
  CheckInResponseDto,
  AttendanceRecordResponseDto,
  LeaveRequestResponseDto,
  QrTokenResponseDto,
  OrderResponseDto,
  PaginatedOrderResponseDto,
  PaymentCallbackDto,
  AttendanceStatisticsResponseDto,
  LessonStatisticsResponseDto,
  RevenueStatisticsResponseDto,
  HealthResponseDto,
  ReadinessResponseDto,
];
